name: My Starter Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run lint

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    with:
      node: ${{ matrix.nodeversion }}
    secrets: inherit
