name: Reusable Workflow

on:
  workflow_call:            # 🚀 maakt de workflow herbruikbaar
    inputs:                 # optioneel, definieer variabelen
      node:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ inputs.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      - run: npm ci && npm test
